### ISSUE TITLE
No devices found yet...

### ISSUE THREAD

**Issue by kostyanet** [belltown/roku-develop#2]
Having 'No devices found yet...' Manual input of the device IP doesn't help it. (OS X)

**Comment by belltown** [comment]
Are you able to access the device from the console using Telnet to port 8085 at the device's IP address?

**Comment by kostyanet** [comment]
Strange, but today it is easy possible to reach the device in both ways, via telnet and via your excellent tool. Thanks a lot!

**Comment by belltown** [comment]
I'm glad it's now working, and that you're liking the Atom package.

If you interested, I have another project, [VioletBug](https://github.com/belltown/violetbug), that you may find useful for debugging your Roku channels.

**Comment by kostyanet** [comment]
Also a nice useful tool. Thanks!
