### ISSUE TITLE
Symlinks is not working

### ISSUE THREAD

**Issue by AhmedGamal-Inmobly** [belltown/roku-develop#4]
I've symlink inside the project and it's not added to the out zip archive.

I've made a workaround to make it work, check this pull request #3

**Comment by belltown** [comment]
Thanks for reporting the issue. I'll take a look at it later today.

**Comment by belltown** [comment]
I've merged your pull request into the GitHub repo, and plan to release the updated Atom package later today.

**Comment by AhmedGamal-Inmobly** [comment]
Great ! 👍

**Comment by belltown** [comment]
Fixed in Atom roku-develop package version 0.1.7. (#3)
