### ISSUE TITLE
Upload error with ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by zeronil** [belltown/roku-develop#5]
Hi,

I'm working on a Roku project that is rather large (the bundle.zip is currently 2 MB) and when I deploy to a Roku Premiere I get an error: "Upload error for 172.18.2.173: ESOCKETTIMEDOUT".

The file does upload to the Roku, but I was wondering if there is a way to change the timeout value or suppress the timeout message since it's a bit of a pain to have to clear the message all of the time.

I use your Atom plug-in everyday and really appreciate the time you took to write it and and make it available. 

Thanks,

Paul

**Comment by belltown** [comment]
Thanks for reporting this issue. I’m away from home right now. I’ll look into it when I return home in the middle of next week.

**Comment by belltown** [comment]
I've changed the timeout value from 15 seconds to 60 seconds in version 0.1.9: https://github.com/belltown/roku-develop/commit/be6a34182a8df626e08e85688828effb92ab3fff.

Let me know if that fixes your problem.

**Comment by zeronil** [comment]
Works great now! Thank you very much!
