### ISSUE TITLE
Where is the add device button?

### ISSUE THREAD

**Issue by simon-grantham** [belltown/roku-develop#8]
Auto discovery may not work in the face of multiple NICs.  I've turned off auto discovery and want to add a device IP.  There is no place I can see to put in an IP and there is no Add New Device button.

**Comment by belltown** [comment]
When you toggle the device list panel using `Ctrl-semicolon` or `right-click -> Toggle device list` or `Packages -> roku-develop -> Toggle device list`, you should see three buttons on the left side of the panel: `Add Device`, `Clear List`, and `Hide Unchecked`. If you see something different then I'd like to see a screenshot of what you have displayed there.

**Comment by simon-grantham** [comment]
Awesome Thx!  You've saved a bunch of us.
